In [6]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import sqlite3
from sklearn.metrics import confusion_matrix
import gc

In [2]:
for i in range(1,11):
    gc.collect()
    cur1 = sqlite3.connect("2019-0{}.sqlite".format(i))
    init_agg_df = pd.read_sql_query("SELECT vendorid, passenger_count,trip_distance, ratecodeid, pulocationid, dolocationid, fare_amount, extra, mta_tax,tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, payment_type FROM tripdata", cur1)
    init_agg_df.to_csv("data_{}.csv".format(i))
    del init_agg_df

1
2
3
4
5
6
7
8
9
10


In [3]:
y_data = init_agg_df["payment_type"].values
init_agg_df = init_agg_df[["vendorid", "passenger_count","trip_distance", "ratecodeid", "pulocationid", "dolocationid", "fare_amount", "extra", "mta_tax","tip_amount", "tolls_amount", "improvement_surcharge", "total_amount", "congestion_surcharge"]].values

In [4]:
means = np.mean(init_agg_df, axis=0)
std = np.std(init_agg_df, axis = 0)
init_agg_df = (init_agg_df - means)/std

In [5]:
init_agg_df = init_agg_df[:,:-1]

In [6]:
train_data_x = init_agg_df[:7000000,:]
train_data_y = y_data[:7000000]
test_data_x = init_agg_df[7000000:,:]
test_data_y = y_data[7000000:]

In [7]:
model = KNeighborsClassifier(n_jobs=-1, n_neighbors=8).fit(train_data_x, train_data_y)

In [14]:
model.score(test_data_x, test_data_y)

0.9703290845053549

In [15]:
print(set(train_data_y.flatten().tolist()))

{1.0, 2.0, 3.0, 4.0}


In [8]:
print(confusion_matrix(test_data_y, model.predict(test_data_x)))

[[489987  14782     14      1]
 [  1835 157449    190     19]
 [    66   2098    493     60]
 [    18    553    178     49]]
